from __future__ import annotations

import enum
import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, String, Text, func, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.shared.db.base import Base


class ActivityStatus(str, enum.Enum):
    draft = "draft"
    published = "published"


class Activity(Base):
    """A group of exercises generated by AI or created manually by a docente.

    Schema: operational.
    """

    __tablename__ = "activities"
    __table_args__ = {"schema": "operational"}

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    course_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("operational.courses.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    created_by: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("operational.users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    prompt_used: Mapped[str | None] = mapped_column(
        Text, nullable=True, comment="Original docente instruction for AI generation",
    )
    status: Mapped[ActivityStatus] = mapped_column(
        Enum(ActivityStatus, name="activity_status", schema="operational"),
        nullable=False,
        default=ActivityStatus.draft,
        server_default=text("'draft'"),
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default=text("true"),
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now(),
    )

    # Relationships
    course: Mapped["Course"] = relationship("Course", foreign_keys=[course_id])
    creator: Mapped["User"] = relationship("User", foreign_keys=[created_by])
    exercises: Mapped[list["Exercise"]] = relationship(
        "Exercise", back_populates="activity", foreign_keys="Exercise.activity_id",
    )

    def __repr__(self) -> str:
        return f"<Activity id={self.id} title={self.title!r} status={self.status.value}>"
